### ISSUE TITLE
Add react and webpack to the solution

### ISSUE THREAD

**Issue by locksmithdon** [kahikatea-2016/friday-projects#18]
This is about getting the mechanics of webpack and React in place. 

- [x] `npm i webpack react react-dom babel-loader babel-preset-es2015 babel-preset-react --save-dev`
- [x] Create the `webpack.config.js`
- [x] Ensure there is a `<div id="app"></div>` in `public/index.html`
- [x] Add `<script src="bundle.js"></script>` to `public/index.html`
- [x] Create a simple `client/App.jsx`
- [x] Create a `client/index.js` that renders `<App />` to `#app` in `public/index.html`
- [x] Add `bundle*` to `.gitignore`
- [x] Ensure the `bundle.js` and `bundle.js.map` files are being created in `public`.
- [x] Ensure the `<App />` components is being rendered to `public/index.html`

**Comment by tina-trenkner** [comment]
Need to decide if it's time to rename list.html to index.html

**Comment by tina-trenkner** [comment]
Should we start a components dir within the client dir for App.jsx?
